name: cache_manager
description: "A globally shared cache for storing and reusing logical data or objects by type and key."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/flutter_cache

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0